CREATE TABLE KG(
    ID NUMBER PRIMARY KEY,
    TEXT VARCHAR2(512),
    EMBEDDING VECTOR,
    METADATA VARCHAR2(255),
    OBJECT_1 VARCHAR2(255),
    RELATION VARCHAR2(255),
    OBJECT_2 VARCHAR2(255)
);

CREATE TABLE DOCUMENTS(
    ID NUMBER PRIMARY KEY,
    DOCUMENT VARCHAR2(255),
    DATA CLOB
);

CREATE TABLE DOC_CHUNKS(
    ID NUMBER PRIMARY KEY,
    DOC VARCHAR2(255),
    CHUNK VARCHAR2(4000),
    VEC VECTOR
);
